// ─── FloodMAS — Report Generation Route ──────────────────────────────
// POST /api/report — takes a chat session's messages and generates a
// professional flood assessment report using the coordinator.

import { Router } from 'express';
import { randomUUID } from 'crypto';
import { runCoordinator } from '../agents/coordinator.js';
import { logger } from '../logger.js';
import { GUARDRAILS } from '../agents/config.js';
import type { ChatSession, AgentEvent } from '../agents/types.js';

const router = Router();

const sessions = new Map<string, ChatSession>();

setInterval(() => {
  const now = Date.now();
  for (const [id, session] of sessions) {
    if (session.done && session.listeners.size === 0 && now - session.createdAt > GUARDRAILS.sessionTtlMs) {
      sessions.delete(id);
    }
  }
}, 60_000);

router.post('/', (req, res) => {
  const { conversationSummary } = req.body as { conversationSummary?: string };
  if (!conversationSummary?.trim()) {
    res.status(400).json({ error: 'conversationSummary is required' });
    return;
  }

  const sanitised = conversationSummary.trim().slice(0, 8000);

  const reportPrompt = `You are generating a PROFESSIONAL FLOOD ASSESSMENT REPORT based on the following conversation and findings.

CONVERSATION CONTEXT:
${sanitised}

Generate a comprehensive, professional report in Markdown format suitable for official submission. Use the following structure:

# FloodMAS — Flood Risk Assessment Report

**Generated:** ${new Date().toISOString().split('T')[0]}
**Classification:** OFFICIAL

## Executive Summary
A 2-3 paragraph overview of the key findings.

## Current Conditions
### Weather & Precipitation
### River Levels & Flow
### Sensor Network Status

## Risk Assessment
### Flood Zone Analysis
### Infrastructure Vulnerability
### Population Impact

## Recommendations
### Immediate Actions (0–24 hours)
### Short-term Actions (1–7 days)
### Long-term Considerations

## Appendix
### Data Sources
### Agent Activity Summary
### Methodology Notes

---
*Report generated by FloodMAS Multi-Agent System*
*This is an automated assessment and should be reviewed by qualified personnel.*

Gather all available data from your tools to make the report as complete and data-driven as possible. Use tables where appropriate.`;

  const sessionId = randomUUID();
  const session: ChatSession = { events: [], done: false, listeners: new Set(), createdAt: Date.now() };
  sessions.set(sessionId, session);

  const emit = (ev: Omit<AgentEvent, 'timestamp'>) => {
    const event: AgentEvent = { ...ev, timestamp: new Date().toISOString() };
    session.events.push(event);
    for (const listener of session.listeners) {
      listener(event);
    }
  };

  const timeout = setTimeout(() => {
    if (!session.done) {
      logger.warn({ sessionId }, 'Report generation timed out');
      emit({ type: 'error', agent: 'System', content: 'Report generation timed out.' });
      session.done = true;
    }
  }, GUARDRAILS.queryTimeoutMs);

  runCoordinator(reportPrompt, emit)
    .catch((err: unknown) => {
      const msg = err instanceof Error ? err.message : String(err);
      logger.error({ err, sessionId }, 'Report generation error');
      emit({ type: 'error', agent: 'System', content: msg });
    })
    .finally(() => {
      clearTimeout(timeout);
      session.done = true;
    });

  res.json({ sessionId });
});

// SSE stream for report generation
router.get('/:id', (req, res) => {
  const session = sessions.get(req.params.id);
  if (!session) {
    res.status(404).json({ error: 'Session not found' });
    return;
  }

  res.writeHead(200, {
    'Content-Type': 'text/event-stream',
    'Cache-Control': 'no-cache',
    Connection: 'keep-alive',
    'X-Accel-Buffering': 'no',
  });

  const send = (event: AgentEvent) => {
    res.write(`data: ${JSON.stringify(event)}\n\n`);
  };

  for (const ev of session.events) {
    send(ev);
  }

  if (session.done) {
    res.write('data: [DONE]\n\n');
    res.end();
    return;
  }

  const listener = (event: AgentEvent) => {
    send(event);
    if (event.type === 'stream_end' || event.type === 'error') {
      res.write('data: [DONE]\n\n');
      res.end();
    }
  };

  session.listeners.add(listener);
  req.on('close', () => {
    session.listeners.delete(listener);
  });
});

export default router;
